#!/usr/bin/env python
# (C) Copyright 2025- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.

import argparse
import importlib
import logging
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Strace IO analysis and replay tool")
    parser.add_argument(
        "-v",
        "--verbose",
        help="Enables verbose output, add -vv to get even more verbose output.",
        action="count",
        default=0,
    )
    parser.add_argument(
        "-p", "--progress", help="Enables progress output", action="store_true"
    )
    sub_parsers = parser.add_subparsers(dest="cmd", required=True)
    commands = (Path(__file__).parent / "commands").glob("*.py")
    for command in commands:
        mod = importlib.import_module(f"commands.{command.stem}")
        getattr(mod, "register")(sub_parsers)

    args = parser.parse_args()

    if args.verbose == 0:
        log_level = logging.WARNING
    elif args.verbose == 1:
        log_level = logging.INFO
    else:
        log_level = logging.DEBUG

    logging.basicConfig(
        format="[%(asctime)s] <%(levelname)s> %(message)s",
        stream=sys.stdout,
        level=log_level,
    )
    log = logging.getLogger(__name__)
    try:
        args.func(args)
    except Exception as e:
        log.error(e)
        log.exception(e)
        sys.exit(1)


if __name__ == "__main__":
    main()
